#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
if [ "${RUN_MIGRATIONS:-0}" = "1" ]; then

    python manage.py makemigrations
    python manage.py migrate
    python manage.py collectstatic --noinput
    python manage.py minimal_actions
    python manage.py minimal_material
    python manage.py patient_information
    python manage.py loaddata patient_states.json
    python manage.py create_debug_exercise
fi

exec "$@"
