#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset
if [ "${RUN_MIGRATIONS:-0}" = "1" ]; then

    python manage.py makemigrations
    python manage.py migrate
    python manage.py collectstatic --noinput
    python manage.py minimal_actions
fi

exec "$@"
