# Generated by Django 5.0.1 on 2024-03-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(max_length=6, unique=True)),
                ('state', models.CharField(choices=[('C', 'configuration'), ('R', 'running'), ('P', 'paused'), ('F', 'finished')], default='C')),
            ],
        ),
        migrations.CreateModel(
            name='SavedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_exercise', models.JSONField()),
                ('name', models.CharField(unique=True)),
                ('time_speed_up', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Max Mustermann', max_length=100)),
                ('patientCode', models.IntegerField(help_text='patientCode used to log into patient - therefore part of authentication')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='game.exercise')),
                ('patient_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='game.patient')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.savedexercise'),
        ),
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('method_name', models.CharField(max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.exercise')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='game.owner')),
            ],
            options={
                'ordering': ['exercise', 'date'],
            },
        ),
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateID', models.IntegerField(help_text='state number as it is used in original data set')),
                ('data', models.JSONField(help_text='data for patient in current phase')),
                ('phase', models.IntegerField(help_text='current phase, e.g. 3')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.patient')),
            ],
            options={
                'unique_together': {('stateID', 'patientID')},
            },
        ),
    ]
