# Generated by Django 5.0.1 on 2024-01-29 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.exercise",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(default="Max Mustermann", max_length=100),
        ),
    ]
