# Generated by Django 5.0.1 on 2024-05-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='frontend_id',
            field=models.CharField(editable=False, unique=True),
        ),
    ]
