# Generated by Django 5.0.1 on 2024-01-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stateID",
                    models.IntegerField(
                        help_text="state number as it is used in original data set"
                    ),
                ),
                (
                    "data",
                    models.JSONField(help_text="data for patient in current phase"),
                ),
                ("phase", models.IntegerField(help_text="current phase, e.g. 3")),
                (
                    "patientID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.patientinstance",
                    ),
                ),
            ],
            options={
                "unique_together": {("stateID", "patientID")},
            },
        ),
    ]
