# Generated by Django 5.0.1 on 2024-01-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedexercise",
            old_name="savedExercise",
            new_name="saved_exercise",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="config",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.savedexercise",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="invitation_code",
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
