# Generated by Django 5.0.1 on 2024-01-25 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_patientstate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PatientInstance",
            new_name="Patient",
        ),
    ]
