# Generated by Django 5.0.1 on 2024-05-28 14:26
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_exercise_frontend_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="personnel",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("lab__isnull", False),
                        ("patient_instance__isnull", True),
                        ("area__isnull", True),
                    ),
                    models.Q(
                        ("patient_instance__isnull", False),
                        ("area__isnull", True),
                        ("lab__isnull", True),
                    ),
                    models.Q(
                        ("area__isnull", False),
                        ("patient_instance__isnull", True),
                        ("lab__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_field_not_null_assignable",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="personnel",
            name="exactly_one_field_not_null_assignable",
        ),
        migrations.AddField(
            model_name="patientinstance",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.lab",
            ),
        ),
        migrations.AlterField(
            model_name="patientinstance",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.area",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="materialinstance",
            name="one_or_more_field_not_null_material",
        ),
    ]
