# Generated by Django 5.0.1 on 2024-03-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_patient_patientcode_patient_patientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='invitation_code',
            new_name='exerciseId',
        ),
    ]
