# Generated by Django 5.0.1 on 2024-01-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_rename_savedexercise_savedexercise_saved_exercise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="invitation_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
