# Generated by Django 5.0.1 on 2024-01-25 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_alter_exercise_invitation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.savedexercise",
            ),
        ),
    ]
