# Generated by Django 5.0.6 on 2024-06-05 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_personnel_exactly_one_field_not_null_assignable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
