# Generated by Django 5.0.1 on 2024-05-29 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_personnel_exactly_one_field_not_null_assignable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actioninstance",
            old_name="area",
            new_name="destination_area",
        ),
    ]
