# Generated by Django 5.0.1 on 2024-03-21 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_scheduledevent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='owner',
        ),
        migrations.AddField(
            model_name='owner',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='game.scheduledevent'),
            preserve_default=False,
        ),
    ]
