# Generated by Django 5.0.1 on 2024-06-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_exercise_trainer"),
        ("game", "0004_rename_area_actioninstance_destination_area"),
    ]

    operations = []
