# Generated by Django 5.0.1 on 2024-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_scheduledevent_owner_owner_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='invitation_code',
            new_name='exerciseId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patientCode',
        ),
        migrations.AddField(
            model_name='patient',
            name='patientId',
            field=models.IntegerField(default=1, help_text='patientId used to log into patient - therefore part of authentication'),
            preserve_default=False,
        ),
    ]
