# Generated by Django 5.0.1 on 2024-03-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_scheduledevent_owner_owner_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('isPaused', models.BooleanField()),
                ('exerciseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.exercise')),
            ],
        ),
    ]
