# Generated by Django 5.0.1 on 2024-03-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_scheduledevent_owner_owner_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientstate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patientstate',
            name='patientID',
        ),
    ]
