# Generated by Django 5.0.1 on 2024-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_alter_exercise_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedexercise",
            name="name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="savedexercise",
            name="saved_exercise",
            field=models.JSONField(),
        ),
    ]
