# Generated by Django 5.0.1 on 2024-03-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_invitation_code_exercise_exerciseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='triage',
            field=models.CharField(choices=[('-', 'undefined'), ('R', 'red'), ('Y', 'yellow'), ('G', 'green'), ('A', 'airway'), ('B', 'breathing'), ('C', 'circulation'), ('D', 'disability'), ('E', 'exposure')], default='-'),
        ),
    ]
