# Generated by Django 5.0.1 on 2024-03-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_patientstate_unique_together_and_more'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='stateID',
            field=models.OneToOneField(default=101, null=True, on_delete=django.db.models.deletion.SET_NULL, to='template.patientstate'),
        ),
        migrations.DeleteModel(
            name='PatientState',
        ),
    ]
