# Generated by Django 5.0.1 on 2024-06-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20240606_1302'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='area',
            name='unique_area_names_per_exercise',
        ),
    ]
