# Generated by Django 5.0.1 on 2024-01-26 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_savedexercise_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedexercise",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
