# Generated by Django 5.0.1 on 2024-08-29 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_area_unique_area_names_per_exercise'),
        ('template', '0011_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinstance',
            name='patient_state',
        ),
        migrations.RemoveField(
            model_name='patientinstance',
            name='static_information',
        ),
        migrations.RemoveField(
            model_name='patientinstance',
            name='triage',
        ),
        migrations.AddField(
            model_name='patientinstance',
            name='patient_state_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientinstance',
            name='patient_template',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='template.patient'),
            preserve_default=False,
        ),
    ]
