# Generated by Django 5.0.1 on 2024-09-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("game", "0006_remove_area_unique_area_names_per_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialinstance",
            name="moved_from_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="materialinstance",
            name="moved_from_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="moved_from_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="personnel",
            name="moved_from_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
