# Generated by Django 5.0.1 on 2025-04-13 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_area_unique_area_names_per_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='timeout',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
