# Generated by Django 5.0.1 on 2024-04-03 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_area"),
        ("game", "0006_patient_triage"),
    ]

    operations = []
