# Generated by Django 5.0.1 on 2025-04-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_area_unique_area_names_per_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='locked_by',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
