# Generated by Django 5.0.1 on 2024-03-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_invitation_code_exercise_exerciseid_and_more'),
        ('game', '0006_patient_stateid_delete_patientstate'),
    ]

    operations = [
    ]
