# Generated by Django 5.0.1 on 2024-04-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_patient_triage'),
        ('game', '0006_personnel'),
    ]

    operations = [
    ]
