# Generated by Django 5.0.1 on 2024-04-03 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_merge_0005_area_0006_patient_triage"),
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="owner",
            name="area_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_events",
                to="game.area",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.area",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_state",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="template.patientstate",
            ),
        ),
        migrations.DeleteModel(
            name="PatientState",
        ),
    ]
