# Generated by Django 5.0.1 on 2024-08-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_patientinstance_patient_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinstance',
            name='triage',
            field=models.CharField(choices=[('-', 'Gray'), ('X', 'Black'), ('1', 'Red'), ('2', 'Yellow'), ('3', 'Green')], default='-'),
        ),
    ]
