# Generated by Django 5.0.1 on 2024-04-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_area"),
        ("game", "0006_patient_triage"),
        ("game", "0007_merge_20240325_1625"),
    ]

    operations = []
