# Generated by Django 5.0.1 on 2026-03-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_scheduledevent_locked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledevent',
            name='locked_by',
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='enqueued',
            field=models.BooleanField(default=False),
        ),
    ]
