# Generated by Django 5.0.1 on 2024-04-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_0006_patient_triage_0006_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='assigned_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.patient'),
        ),
    ]
