# Generated by Django 5.0.1 on 2024-04-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_owner_area_owner_patient_area_patient_patient_state_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="area",
            old_name="exerciseId",
            new_name="exercise",
        ),
    ]
