# Generated by Django 5.0.1 on 2024-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_patientinstance_triage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_state_id',
            field=models.CharField(help_text='State of the patient', max_length=16),
        ),
    ]
