# Generated by Django 5.0.1 on 2024-04-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_merge_20240402_1655"),
        ("template", "0002_actiontype_patientstate_is_dead_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="stateID",
        ),
        migrations.AddField(
            model_name="patient",
            name="patient_state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="template.patientstate",
            ),
        ),
        migrations.CreateModel(
            name="AppliedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PL", "planned"),
                            ("IP", "in_progress"),
                            ("FI", "finished"),
                            ("AC", "active"),
                            ("DE", "declined"),
                            ("CA", "canceled"),
                        ],
                        default="PL",
                        max_length=2,
                    ),
                ),
                (
                    "reason_of_declination",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("result", models.JSONField(blank=True, default=None, null=True)),
                (
                    "action_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="template.actiontype",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.patient"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="owner",
            name="applied_action_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_events",
                to="game.appliedaction",
            ),
        ),
    ]
