# Generated by Django 5.0.1 on 2024-09-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_patientinstance_patient_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_state_id',
            field=models.CharField(blank=True, help_text='State of the patient', max_length=16, null=True),
        ),
    ]
