# Generated by Django 5.0.1 on 2024-04-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_personnel_assigned_patient'),
        ('game', '0009_rename_exerciseid_area_exercise'),
    ]

    operations = [
    ]
