# Generated by Django 5.0.1 on 2024-04-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_remove_patient_stateid_patient_patient_state_and_more"),
        ("template", "0002_actiontype_patientstate_is_dead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.area",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_state",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="template.patientstate",
            ),
        ),
    ]
