# Generated by Django 5.0.1 on 2024-04-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_merge_20240405_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.scheduledevent'),
        ),
    ]
