# Generated by Django 5.0.1 on 2024-04-10 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_owner_event'),
        ('template', '0008_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PL', 'planned'), ('IP', 'in_progress'), ('FI', 'finished'), ('AC', 'active'), ('DE', 'declined'), ('CA', 'canceled')], default='PL', max_length=2)),
                ('reason_of_declination', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.action')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AppliedActionTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(choices=[('PL', 'planned'), ('IP', 'in_progress'), ('FI', 'finished'), ('AC', 'active'), ('DE', 'declined'), ('CA', 'canceled')], max_length=2)),
                ('t_local_begin', models.IntegerField(blank=True, null=True)),
                ('t_local_end', models.IntegerField(blank=True, null=True)),
                ('applied_action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.appliedaction')),
            ],
        ),
    ]
