# Generated by Django 5.0.1 on 2024-04-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_appliedaction_appliedactiontimestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedaction',
            old_name='action_type',
            new_name='action_template',
        ),
    ]
