# Generated by Django 5.0.1 on 2024-04-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_rename_action_type_appliedaction_action_template'),
        ('template', '0009_alter_action_category_alter_action_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppliedAction',
            new_name='ActionInstance',
        ),
        migrations.RenameModel(
            old_name='AppliedActionTimestamp',
            new_name='ActionInstanceTimestamp',
        ),
    ]
