# Generated by Django 5.0.1 on 2024-04-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_appliedaction_actioninstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='action_instance_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='game.actioninstance'),
        ),
    ]
