# Generated by Django 5.0.1 on 2024-04-12 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_owner_action_instance_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioninstance',
            name='state',
        ),
        migrations.CreateModel(
            name='ActionInstanceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PL', 'planned'), ('IP', 'in_progress'), ('OH', 'on_hold'), ('FI', 'finished'), ('AC', 'active'), ('DE', 'declined'), ('CA', 'canceled')], max_length=2)),
                ('t_local_begin', models.IntegerField()),
                ('t_local_end', models.IntegerField(blank=True, null=True)),
                ('info_text', models.CharField(blank=True, default=None, null=True)),
                ('action_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='game.actioninstance')),
            ],
        ),
        migrations.AddField(
            model_name='actioninstance',
            name='current_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.actioninstancestate'),
        ),
        migrations.DeleteModel(
            name='ActionInstanceTimestamp',
        ),
    ]
