# Generated by Django 5.0.1 on 2024-04-14 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_remove_actioninstance_state_actioninstancestate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioninstance',
            name='reason_of_declination',
        ),
        migrations.AddField(
            model_name='actioninstance',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
        migrations.AlterField(
            model_name='actioninstance',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patient'),
        ),
    ]
