# Generated by Django 5.0.1 on 2024-04-15 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_remove_actioninstance_reason_of_declination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninstancestate',
            name='action_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.actioninstance'),
        ),
    ]
