# Generated by Django 5.0.1 on 2024-04-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_actioninstancestate_action_instance'),
        ('template', '0010_rename_duration_action_application_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='PatientInstance',
        ),
    ]
