# Generated by Django 5.0.1 on 2024-04-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_rename_patient_patientinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinstance',
            old_name='patientId',
            new_name='patient_id',
        ),
    ]
