# Generated by Django 5.0.1 on 2024-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_rename_patientid_patientinstance_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_id',
            field=models.IntegerField(help_text='patient_id used to log into patient - therefore part of authentication'),
        ),
    ]
