# Generated by Django 5.0.1 on 2024-04-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_patientinstance_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actioninstance',
            old_name='patient',
            new_name='patient_instance',
        ),
    ]
