# Generated by Django 5.0.1 on 2024-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_rename_patient_actioninstance_patient_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_id',
            field=models.IntegerField(help_text='patient_id used to log into patient - therefore part of authentication', unique=True),
        ),
    ]
