# Generated by Django 5.0.1 on 2024-04-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_alter_patientinstance_patient_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patientinstance",
            old_name="patient_id",
            new_name="patient_frontend_id",
        ),
    ]
