# Generated by Django 5.0.1 on 2024-04-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_alter_patientinstance_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninstancestate',
            name='name',
            field=models.CharField(choices=[('PL', 'planned'), ('IP', 'in_progress'), ('OH', 'on_hold'), ('FI', 'finished'), ('AC', 'active'), ('EX', 'expired'), ('DE', 'declined'), ('CA', 'canceled')], max_length=2),
        ),
    ]
