# Generated by Django 5.0.1 on 2024-04-18 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0023_alter_patientinstance_patient_id"),
    ]

    operations = []
