# Generated by Django 5.0.1 on 2024-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20240422_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_frontend_id',
            field=models.IntegerField(help_text='patient_frontend_id used to log into patient - therefore part of authentication', unique=True),
        ),
    ]
