# Generated by Django 5.0.1 on 2024-04-24 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_actioninstancestate_name'),
        ('template', '0015_rename_gets_consumed_resource_is_returnable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.area')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game.inventory')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.resource')),
            ],
        ),
    ]
