# Generated by Django 5.0.1 on 2024-05-03 11:42

import django.db.models.deletion
import helpers.local_timable
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_actioninstancestate_name'),
        ('template', '0017_resource_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='action_instance_owner',
        ),
        migrations.RemoveField(
            model_name='actioninstancestate',
            name='action_instance',
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consuming_inventory', to='game.area')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumning_inventory', to='game.patientinstance')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='game.inventory')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consuming_inventory', to='game.lab'),
        ),
        migrations.CreateModel(
            name='LabActionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.action')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.actioninstancestate')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab')),
                ('patient_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patientinstance')),
            ],
            options={
                'abstract': False,
            },
            bases=(helpers.local_timable.LocalTimeable, models.Model),
        ),
        migrations.AddField(
            model_name='actioninstancestate',
            name='lab_action_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.labactioninstance'),
        ),
        migrations.AddField(
            model_name='owner',
            name='lab_action_instance_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='game.labactioninstance'),
        ),
        migrations.CreateModel(
            name='PatientActionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.action')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area')),
                ('current_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.actioninstancestate')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab')),
                ('patient_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patientinstance')),
            ],
            options={
                'abstract': False,
            },
            bases=(helpers.local_timable.LocalTimeable, models.Model),
        ),
        migrations.AddField(
            model_name='actioninstancestate',
            name='patient_action_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='game.patientactioninstance'),
        ),
        migrations.AddField(
            model_name='owner',
            name='patient_action_instance_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='game.patientactioninstance'),
        ),
        migrations.DeleteModel(
            name='ActionInstance',
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('patient__isnull', False), ('area__isnull', False), ('lab__isnull', False), _connector='OR'), name='one_or_more_field_not_null_inventory'),
        ),
    ]
