# Generated by Django 5.0.1 on 2024-04-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_actioninstancestate_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actioninstance',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='actioninstance',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
