# Generated by Django 5.0.1 on 2024-04-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_actioninstancestate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='kwargs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
