# Generated by Django 5.0.1 on 2024-04-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_alter_patientinstance_patient_frontend_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exerciseId',
            new_name='exercise_frontend_id',
        ),
    ]
