# Generated by Django 5.0.1 on 2024-04-25 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_inventory_inventoryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consuming_inventory', to='game.area'),
        ),
    ]
