# Generated by Django 5.0.1 on 2024-05-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_remove_owner_action_instance_owner_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(check=models.Q(('lab_action_instance_owner__isnull', False), ('patient_owner__isnull', False), ('exercise_owner__isnull', False), ('area_owner__isnull', False), ('patient_action_instance_owner__isnull', False), _connector='OR'), name='one_or_more_field_not_null_owner'),
        ),
    ]
