# Generated by Django 5.0.1 on 2024-04-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0025_alter_actioninstance_options_actioninstance_order_id"),
        ("template", "0012_alter_patientstate_transition"),
    ]

    operations = []
