# Generated by Django 5.0.1 on 2024-05-03 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_owner_one_or_more_field_not_null_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consuming_inventory', to='game.patientinstance'),
        ),
    ]
