# Generated by Django 5.0.1 on 2024-04-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_alter_actioninstancestate_name'),
        ('game', '0026_rename_exerciseid_exercise_exercise_frontend_id'),
    ]

    operations = [
    ]
