# Generated by Django 5.0.1 on 2024-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_inventory_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryentry',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
