# Generated by Django 5.0.1 on 2024-04-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_inventoryentry_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consuming_inventory', to='game.area'),
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='game.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consuming_inventory', to='game.lab'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('area__isnull', False), ('lab__isnull', False), _connector='OR'), name='at_least_one_field_not_null'),
        ),
    ]
