# Generated by Django 5.0.1 on 2024-04-25 09:16

import django.db.models.deletion
import game.models.patient_instance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_merge_20240422_1917'),
        ('template', '0013_patientinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinstance',
            name='static_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='template.patientinformation'),
        ),
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_frontend_id',
            field=models.IntegerField(default=game.models.patient_instance.generate_secure_random_id, help_text='patient_frontend_id used to log into patient - therefore part of authentication', unique=True),
        ),
    ]
