# Generated by Django 5.0.1 on 2024-05-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_alter_inventory_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='patient',
            new_name='patient_instance',
        ),
    ]
