# Generated by Django 5.0.1 on 2024-04-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_actioninstance_unique_order_id_for_patient'),
        ('game', '0028_patientinstance_static_information_and_more'),
    ]

    operations = [
    ]
