# Generated by Django 5.0.1 on 2024-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_rename_patient_inventory_patient_instance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventory',
            name='one_or_more_field_not_null_inventory',
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('patient_instance__isnull', False), ('area__isnull', False), ('lab__isnull', False), _connector='OR'), name='one_or_more_field_not_null_inventory'),
        ),
    ]
