# Generated by Django 5.0.1 on 2024-05-03 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_remove_inventory_one_or_more_field_not_null_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='area',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='lab',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='patient_instance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patientinstance'),
        ),
    ]
