# Generated by Django 5.0.1 on 2024-04-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_merge_20240429_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='game.exercise'),
        ),
        migrations.AlterField(
            model_name='patientinstance',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='game.area'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to='game.area'),
        ),
    ]
