# Generated by Django 5.0.1 on 2024-04-29 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_alter_area_exercise_alter_patientinstance_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.exercise'),
        ),
        migrations.AlterField(
            model_name='patientinstance',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
    ]
