# Generated by Django 5.0.1 on 2024-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_remove_inventory_at_least_one_field_not_null_and_more'),
        ('template', '0017_resource_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='actioninstance',
            name='one_field_not_null_action_instance',
        ),
        migrations.RemoveConstraint(
            model_name='inventory',
            name='one_field_not_null_inventory',
        ),
        migrations.RemoveConstraint(
            model_name='owner',
            name='one_field_not_null_owner',
        ),
        migrations.AddConstraint(
            model_name='actioninstance',
            constraint=models.CheckConstraint(check=models.Q(('lab__isnull', False), ('patient_instance__isnull', False), ('area__isnull', False), _connector='OR'), name='one_or_more_field_not_null_action_instance'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('patient__isnull', False), ('area__isnull', False), ('lab__isnull', False), _connector='OR'), name='one_or_more_field_not_null_inventory'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(check=models.Q(('action_instance_owner__isnull', False), ('patient_owner__isnull', False), ('exercise_owner__isnull', False), ('area_owner__isnull', False), _connector='OR'), name='one_or_more_field_not_null_owner'),
        ),
    ]
