# Generated by Django 5.0.1 on 2024-05-03 20:39

from django.db import migrations


def populate_lab_action_instance(apps, schema_editor):
    LabActionInstance = apps.get_model("game", "LabActionInstance")
    Lab = apps.get_model("game", "Lab")
    Exercise = apps.get_model("game", "Exercise")
    junk_exercise, _ = Exercise.objects.get_or_create(exerciseId="junk")
    junk_lab, _ = Lab.objects.get_or_create(exercise=junk_exercise, name="junk")
    for action_instance in LabActionInstance.objects.all():
        action_instance.lab = junk_lab
        action_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0031_remove_inventory_one_or_more_field_not_null_inventory_and_more"),
    ]

    operations = [migrations.RunPython(populate_lab_action_instance)]
