# Generated by Django 5.0.1 on 2024-04-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_remove_actioninstance_one_field_not_null_action_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabActionInstance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.actioninstance',),
        ),
    ]
