# Generated by Django 5.0.1 on 2024-04-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_scheduledevent_kwargs'),
        ('game', '0031_alter_area_exercise_alter_patientinstance_area_and_more'),
    ]

    operations = [
    ]
