# Generated by Django 5.0.1 on 2024-05-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_CUSTOM_populate_lab_action_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labactioninstance',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.lab'),
        ),
    ]
