# Generated by Django 5.0.1 on 2024-04-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_labactioninstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaActionInstance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.actioninstance',),
        ),
    ]
