# Generated by Django 5.0.1 on 2024-05-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_merge_20240429_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioninstancestate',
            name='name',
            field=models.CharField(choices=[('PL', 'planned'), ('IP', 'in_progress'), ('OH', 'on_hold'), ('FI', 'finished'), ('IE', 'in effect'), ('EX', 'expired'), ('CA', 'canceled')], max_length=2),
        ),
    ]
