# Generated by Django 5.0.1 on 2024-05-03 20:56

from django.db import migrations


def populate_inventories(apps, schema_editor):
    Inventory = apps.get_model("game", "Inventory")
    Lab = apps.get_model("game", "Lab")
    Area = apps.get_model("game", "Area")
    PatientInstance = apps.get_model("game", "PatientInstance")
    missing_inventory_objects = []
    missing_inventory_objects += Lab.objects.filter(inventory=None)
    missing_inventory_objects += Area.objects.filter(inventory=None)
    missing_inventory_objects += PatientInstance.objects.filter(inventory=None)
    for missing_inventory_object in missing_inventory_objects:
        missing_inventory_object.inventory = Inventory.objects.create()
        missing_inventory_object.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0033_alter_labactioninstance_lab"),
    ]

    operations = [
        migrations.RunPython(populate_inventories),
    ]
