# Generated by Django 5.0.1 on 2024-04-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_areaactioninstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaActionInstance',
        ),
        migrations.CreateModel(
            name='PatientActionInstance',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.actioninstance',),
        ),
    ]
