# Generated by Django 5.0.1 on 2024-05-03 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_patientinstance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
