# Generated by Django 5.0.1 on 2024-05-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_actioninstancestate_name'),
        ('template', '0015_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab')),
                ('material_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='template.material')),
                ('patient_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patientinstance')),
            ],
        ),
    ]
