# Generated by Django 5.0.1 on 2024-05-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0033_alter_actioninstancestate_name"),
        ("game", "0033_patientinstance_user"),
    ]

    operations = []
