# Generated by Django 5.0.1 on 2024-05-06 14:06

from django.db import migrations
from helpers.id_generator import LevenshteinCode


def populate_patient_instance_area_relation(apps, schema_editor):
    PatientInstance = apps.get_model("game", "PatientInstance")
    Area = apps.get_model("game", "Area")
    Exercise = apps.get_model("game", "Exercise")
    junk_exercise, _ = Exercise.objects.get_or_create(
        exercise_frontend_id=LevenshteinCode(code_length=1).get_exercise_frontend_id()
    )
    junk_area, _ = Area.objects.get_or_create(
        name="Junk", exercise=junk_exercise, isPaused=False
    )
    for patient_instance in PatientInstance.objects.filter(area=None):
        patient_instance.area = junk_area
        patient_instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0034_lab_materialinstance"),
    ]

    operations = [migrations.RunPython(populate_patient_instance_area_relation)]
