# Generated by Django 5.0.1 on 2024-05-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_delete_areaactioninstance_patientactioninstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioninstance',
            name='lab',
        ),
    ]
