# Generated by Django 5.0.1 on 2024-05-03 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_CUSTOM_populate_inventories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.inventory'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.inventory'),
        ),
        migrations.AlterField(
            model_name='patientinstance',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.inventory'),
        ),
    ]
