# Generated by Django 5.0.1 on 2024-05-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0033_alter_actioninstancestate_name"),
        ("game", "0035_alter_area_inventory_alter_lab_inventory_and_more"),
    ]

    operations = []
