# Generated by Django 5.0.1 on 2024-05-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='message',
            field=models.TextField(default='Database validity message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(blank=True, help_text='May only be set while exercise is running', null=True),
        ),
        migrations.AddConstraint(
            model_name='logentry',
            constraint=models.UniqueConstraint(fields=('local_id', 'exercise'), name='unique_local_id_for_entry'),
        ),
    ]
