# Generated by Django 5.0.1 on 2024-05-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_CUSTOM_enforce_area_for_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='isPaused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patientinstance',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('name', 'exercise'), name='unique_area_names_per_exercise'),
        ),
    ]
