# Generated by Django 5.0.1 on 2024-05-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_merge_20240504_1503'),
        ('template', '0018_merge_20240504_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labactioninstance',
            options={'ordering': ['order_id']},
        ),
        migrations.AddField(
            model_name='labactioninstance',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientactioninstance',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name='patientactioninstance',
            constraint=models.UniqueConstraint(fields=('order_id', 'patient_instance'), name='unique_order_id_for_patient'),
        ),
    ]
