# Generated by Django 5.0.1 on 2024-05-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0034_merge_20240503_1328"),
        ("game", "0036_alter_area_ispaused_alter_area_name_and_more"),
    ]

    operations = []
