# Generated by Django 5.0.1 on 2024-05-05 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0037_alter_labactioninstance_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.IntegerField()),
            ],
            options={
                "ordering": ["order_id"],
            },
        ),
        migrations.AlterModelOptions(
            name="labactioninstance",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="patientactioninstance",
            name="unique_order_id_for_patient",
        ),
        migrations.RemoveField(
            model_name="labactioninstance",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="patientactioninstance",
            name="order_id",
        ),
        migrations.AddField(
            model_name="queue",
            name="patient_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="game.patientinstance"
            ),
        ),
        migrations.AddField(
            model_name="labactioninstance",
            name="queue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.queue",
            ),
        ),
        migrations.AddField(
            model_name="patientactioninstance",
            name="queue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.queue",
            ),
        ),
        migrations.AddConstraint(
            model_name="queue",
            constraint=models.UniqueConstraint(
                fields=("order_id", "patient_instance"),
                name="unique_order_id_for_patient",
            ),
        ),
    ]
