# Generated by Django 5.0.1 on 2024-05-07 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_merge_20240506_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioninstance',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab'),
        ),
    ]
