# Generated by Django 5.0.1 on 2024-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_remove_lab_name_alter_actioninstance_area'),
        ('template', '0016_alter_action_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='materialinstance',
            constraint=models.CheckConstraint(check=models.Q(('lab__isnull', False), ('patient_instance__isnull', False), ('area__isnull', False), _connector='OR'), name='one_or_more_field_not_null_material'),
        ),
    ]
