# Generated by Django 5.0.1 on 2024-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_owner_one_or_more_field_not_null_owner'),
        ('template', '0016_alter_action_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='actioninstance',
            constraint=models.CheckConstraint(check=models.Q(('lab__isnull', False), ('patient_instance__isnull', False), _connector='OR'), name='one_or_more_field_not_null_action'),
        ),
    ]
