# Generated by Django 5.0.1 on 2024-05-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0035_personnel_action_instance_logentry_and_more"),
        ("game", "0042_actioninstance_one_or_more_field_not_null_action"),
    ]

    operations = []
