# Generated by Django 5.0.1 on 2024-05-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0043_CUSTOM_enforce_static_information_for_patient"),
    ]

    operations = []
