# Generated by Django 5.0.1 on 2024-05-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0043_CUSTOM_enforce_static_information_for_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinstance",
            name="patient_frontend_id",
            field=models.CharField(
                help_text="patient_frontend_id used to log into patient - therefore part of authentication. Numeric with leading zeros",
                max_length=6,
                unique=True,
            ),
        ),
    ]
