# Generated by Django 5.0.1 on 2024-05-10 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_merge_20240510_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab'),
        ),
    ]
