# Generated by Django 5.0.1 on 2024-05-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0044_alter_patientinstance_patient_frontend_id"),
    ]

    operations = []
