# Generated by Django 5.0.1 on 2024-05-13 18:21

import game.models.patient_instance
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0044_alter_patientinstance_patient_frontend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='patient_frontend_id',
            field=models.CharField(help_text='patient_frontend_id used to log into patient - see validator for format', max_length=6, unique=True, validators=[game.models.patient_instance.validate_patient_frontend_id]),
        ),
    ]
