# Generated by Django 5.0.1 on 2024-05-13 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_alter_logentry_is_dirty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User object for authentication - has to be deleted explicitly or manually', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
