# Generated by Django 5.0.1 on 2024-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_alter_patientinstance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='patientinstance',
            name='patient_frontend_id',
        ),
        migrations.AddField(
            model_name='patientinstance',
            name='frontend_id',
            field=models.IntegerField(default=123, help_text='frontend_id used to log into patient - therefore part of authentication', unique=True),
            preserve_default=False,
        ),
    ]
