# Generated by Django 5.0.1 on 2024-05-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0045_alter_patientinstance_patient_frontend_id'),
        ('game', '0047_remove_logentry_lab_and_more'),
    ]

    operations = [
    ]
