# Generated by Django 5.0.1 on 2024-05-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0049_alter_patientinstance_static_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='materials',
            field=models.ManyToManyField(blank=True, to='game.materialinstance'),
        ),
    ]
