# Generated by Django 5.0.1 on 2024-05-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_logentry_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinstance',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
        migrations.AlterField(
            model_name='materialinstance',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab'),
        ),
        migrations.AlterField(
            model_name='materialinstance',
            name='patient_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patientinstance'),
        ),
    ]
