# Generated by Django 5.0.1 on 2024-05-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0051_alter_materialinstance_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_frontend_id',
            new_name='frontend_id',
        ),
    ]
