# Generated by Django 5.0.1 on 2024-05-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_rename_exercise_frontend_id_exercise_frontend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
