# Generated by Django 5.0.1 on 2024-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0052_rename_exercise_frontend_id_exercise_frontend_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinstance',
            name='triage',
            field=models.CharField(choices=[('-', 'Gray'), ('X', 'Black'), ('1', 'Red'), ('2', 'Yellow'), ('3', 'Green')], default='-'),
        ),
    ]
