# Generated by Django 5.0.1 on 2024-05-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0054_rename_action_template_actioninstance_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='is_blocked',
        ),
    ]
