# Generated by Django 5.0.1 on 2024-05-17 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0056_materialinstance_action_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialinstance',
            name='is_blocked',
        ),
    ]
