# Generated by Django 5.0.1 on 2024-05-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0057_remove_materialinstance_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='action_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.actioninstance'),
        ),
    ]
