# Generated by Django 5.0.1 on 2024-05-19 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0058_alter_personnel_action_instance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialinstance',
            old_name='material_template',
            new_name='template',
        ),
    ]
