# Generated by Django 5.0.1 on 2024-05-19 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0059_rename_material_template_materialinstance_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialinstance',
            name='action_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.actioninstance'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='action_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.actioninstance'),
        ),
    ]
