# Generated by Django 5.0.1 on 2024-05-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0053_alter_patientinstance_triage'),
        ('game', '0060_alter_materialinstance_action_instance_and_more'),
    ]

    operations = [
    ]
