# Generated by Django 5.0.1 on 2024-05-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_merge_20240520_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='assigned_patient',
        ),
        migrations.AddField(
            model_name='personnel',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.lab'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='patient_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.patientinstance'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.area'),
        ),
    ]
