# Generated by Django 5.0.1 on 2024-05-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_merge_20240520_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='frontend_id',
            field=models.CharField(editable=False, unique=True),
        ),
    ]
