# Generated by Django 5.0.1 on 2024-05-23 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0061_merge_20240520_1337'),
        ('template', '0019_rename_data_patientstate_vital_signs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioninstance',
            name='historic_patient_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='template.patientstate'),
        ),
    ]
