# Generated by Django 5.0.1 on 2024-04-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatientState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stateID",
                    models.IntegerField(
                        help_text="state number as it is used in original data set"
                    ),
                ),
                ("patientID", models.IntegerField()),
                (
                    "data",
                    models.JSONField(help_text="data for patient in current phase"),
                ),
                ("phase", models.IntegerField(help_text="current phase, e.g. 3")),
                ("is_dead", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("stateID", "patientID")},
            },
        ),
    ]
