# Generated by Django 5.0.1 on 2024-03-25 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0005_alter_patientstate_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateID', models.IntegerField(help_text='state number as it is used in original data set')),
                ('data', models.JSONField(help_text='data for patient in current phase')),
                ('phase', models.IntegerField(help_text='current phase, e.g. 3')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='game.patient')),
            ],
            options={
                'unique_together': {('stateID', 'patientID')},
            },
        ),
    ]
