# Generated by Django 5.0.1 on 2024-04-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("duration", models.IntegerField(default=10)),
                ("condition", models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="patientstate",
            name="is_dead",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="patientstate",
            name="patientID",
            field=models.IntegerField(),
        ),
    ]
