# Generated by Django 5.0.1 on 2024-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_owner_area_owner_patient_area_patient_patient_state_and_more"),
        ("template", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="patientstate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="patientstate",
            name="patients",
            field=models.ManyToManyField(related_name="states", to="game.patient"),
        ),
        migrations.AddField(
            model_name="patientstate",
            name="state_phase",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="patientstate",
            name="patientID",
        ),
        migrations.RemoveField(
            model_name="patientstate",
            name="phase",
        ),
    ]
