# Generated by Django 5.0.1 on 2024-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.CharField(choices=[('TR', 'treatment'), ('EX', 'examination'), ('PR', 'production'), ('IM', 'imaging'), ('LA', 'lab'), ('OT', 'other')], max_length=2),
        ),
    ]
