# Generated by Django 5.0.1 on 2024-05-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_material_moveable_material_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='is_reusable',
            new_name='reusable',
        ),
        migrations.RemoveField(
            model_name='material',
            name='used',
        ),
    ]
