# Generated by Django 5.0.1 on 2024-05-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0002_alter_action_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="location",
            field=models.CharField(
                choices=[("LA", "lab"), ("BE", "bedside"), ("ST", "station")],
                default="BE",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="category",
            field=models.CharField(
                choices=[
                    ("TR", "treatment"),
                    ("EX", "examination"),
                    ("PR", "production"),
                    ("IM", "imaging"),
                ],
                max_length=2,
            ),
        ),
    ]
