# Generated by Django 5.0.1 on 2024-04-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_statetransition_patientstate_transition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstate',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='patientstate',
            name='stateID',
        ),
    ]
