# Generated by Django 5.0.1 on 2024-06-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0003_rename_is_reusable_material_reusable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='moveable',
            new_name='is_moveable',
        ),
        migrations.RemoveField(
            model_name='material',
            name='reusable',
        ),
        migrations.AddField(
            model_name='material',
            name='is_reusable',
            field=models.BooleanField(default=False),
        ),
    ]
