# Generated by Django 5.0.1 on 2024-04-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0004_remove_patientstate_patients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statetransition',
            name='resulting_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='template.patientstate'),
        ),
    ]
