# Generated by Django 5.0.1 on 2024-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0004_alter_action_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="relocates",
            field=models.BooleanField(
                default=False,
                help_text="Does the action relocate the patient to the location and back?",
            ),
        ),
        migrations.AlterField(
            model_name="action",
            name="category",
            field=models.CharField(
                choices=[
                    ("TR", "treatment"),
                    ("EX", "examination"),
                    ("PR", "production"),
                    ("OT", "other"),
                ],
                max_length=2,
            ),
        ),
    ]
