# Generated by Django 5.0.1 on 2024-04-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0005_alter_statetransition_resulting_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstate',
            name='stateID',
            field=models.IntegerField(default=0, help_text='For Debugging purposes! State number as it is used in original data set'),
        ),
    ]
