# Generated by Django 5.0.1 on 2024-06-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0004_rename_moveable_material_is_moveable_and_more"),
        ("template", "0005_action_relocates_alter_action_category"),
    ]

    operations = []
