# Generated by Django 5.0.1 on 2024-06-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0006_merge_20240603_1352"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_lab",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="material",
            name="category",
            field=models.CharField(
                choices=[("DE", "Device"), ("BL", "Blood")], max_length=2
            ),
        ),
    ]
