# Generated by Django 5.0.1 on 2024-04-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0006_patientstate_stateid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientstate',
            old_name='state_phase',
            new_name='state_depth',
        ),
    ]
