# Generated by Django 5.0.1 on 2024-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0007_rename_state_phase_patientstate_state_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TR', 'treatment'), ('DI', 'diagnosis')], max_length=2)),
                ('duration', models.IntegerField(default=10, help_text='Duration in seconds in realtime. Might be scaled by external factors.')),
                ('conditions', models.JSONField(blank=True, default=None, null=True)),
            ],
        ),
    ]
