# Generated by Django 5.0.1 on 2024-04-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0008_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.CharField(choices=[('TR', 'treatment'), ('EX', 'examination'), ('LA', 'lab'), ('OT', 'other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
