# Generated by Django 5.0.1 on 2024-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_patientinformation_pretreatment_action_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientinformation",
            name="pretreatment_action_templates",
            field=models.JSONField(default=dict),
        ),
    ]
