# Generated by Django 5.0.1 on 2024-07-10 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0008_remove_patientinformation_consecutive_unique_number"),
        ("template", "0009_alter_patientinformation_pretreatment_action_templates"),
    ]

    operations = []
