# Generated by Django 5.0.1 on 2024-04-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0009_alter_action_category_alter_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
