# Generated by Django 5.0.1 on 2024-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_merge_20240710_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.JSONField()),
                ('flow', models.JSONField()),
                ('states', models.JSONField()),
                ('transitions', models.JSONField()),
                ('components', models.JSONField()),
            ],
        ),
    ]
