# Generated by Django 5.0.1 on 2024-09-12 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0010_merge_20240710_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(choices=[('SpO2', 'Spo2'), ('BPM', 'Heart Rate')], unique=True)),
                ('function', models.CharField(choices=[('linear', 'Linear'), ('increment', 'Increment'), ('decrement', 'Decrement')])),
                ('exceptions', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
