# Generated by Django 5.0.1 on 2025-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0011_alter_patientstate_transition'),
        ('template', '0011_patient'),
    ]

    operations = [
    ]
