# Generated by Django 5.0.1 on 2024-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0011_continuousvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuousvariable',
            name='function',
            field=models.CharField(choices=[('linear', 'Linear'), ('sigmoid', 'Sigmoid'), ('delayed sigmoid', 'Sigmoid Delayed'), ('increment', 'Increment'), ('decrement', 'Decrement')]),
        ),
    ]
