# Generated by Django 5.0.1 on 2024-10-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0011_alter_patientstate_transition"),
        ("template", "0012_alter_continuousvariable_function"),
    ]

    operations = []
