# Generated by Django 5.0.1 on 2024-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0012_alter_patientstate_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Sensen Code', unique=True)),
                ('personal_details', models.CharField(default='-', max_length=300)),
                ('injury', models.CharField(default='-', max_length=300)),
                ('biometrics', models.CharField(default='-', max_length=300)),
                ('triage', models.CharField(choices=[('-', 'undefined'), ('R', 'red'), ('Y', 'yellow'), ('G', 'green'), ('A', 'airway'), ('B', 'breathing'), ('C', 'circulation'), ('D', 'disability'), ('E', 'exposure')], default='-')),
                ('consecutive_unique_number', models.IntegerField(default=-1)),
                ('mobility', models.CharField(default='-', max_length=100)),
                ('preexisting_illnesses', models.CharField(default='-', max_length=300)),
                ('permanent_medication', models.CharField(default='-', max_length=300)),
                ('current_case_history', models.CharField(default='-', max_length=300)),
                ('pretreatment', models.CharField(default='-', max_length=300)),
                ('start_status', models.IntegerField(default=-1)),
                ('start_location', models.CharField(default='-', max_length=100)),
                ('op', models.CharField(default='-', max_length=300)),
            ],
        ),
    ]
