# Generated by Django 5.0.1 on 2024-04-24 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0012_alter_patientstate_transition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gets_blocked', models.BooleanField()),
                ('gets_consumed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
