# Generated by Django 5.0.1 on 2024-05-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0014_merge_0013_action_results_0013_patientinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('upper_limit', models.IntegerField()),
                ('lower_limit', models.IntegerField()),
                ('fulfilling_measures', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='patientstate',
            old_name='stateID',
            new_name='state_id',
        ),
        migrations.RemoveField(
            model_name='patientstate',
            name='state_depth',
        ),
        migrations.AlterField(
            model_name='patientstate',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='template.statetransition'),
        ),
        migrations.CreateModel(
            name='LogicNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('N', 'not'), ('A', 'and'), ('S', 'subcondition'), ('T', 'true')], default='T', max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='template.logicnode')),
                ('state_transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logic_nodes', to='template.statetransition')),
                ('subcondition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logic_nodes', to='template.subcondition')),
            ],
            options={
                'ordering': ['state_transition'],
            },
        ),
    ]
