# Generated by Django 5.0.1 on 2024-05-06 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0014_merge_0013_action_results_0013_patientinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('DE', 'Device'), ('BL', 'Blood')], max_length=2)),
                ('is_reusable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
