# Generated by Django 5.0.1 on 2024-05-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0015_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='category',
            field=models.CharField(choices=[('TR', 'treatment'), ('EX', 'examination'), ('LA', 'lab'), ('PR', 'production'), ('OT', 'other')], max_length=2),
        ),
    ]
