# Generated by Django 5.0.1 on 2024-05-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0015_subcondition_rename_stateid_patientstate_state_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstate',
            name='code',
            field=models.IntegerField(default=0, help_text='Sensen Code'),
        ),
        migrations.AddConstraint(
            model_name='patientstate',
            constraint=models.UniqueConstraint(fields=('code', 'state_id'), name='unique_code_stateid'),
        ),
    ]
