# Generated by Django 5.0.1 on 2024-04-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0016_action_success_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[("DE", "Device"), ("BL", "Blood")], default="DE", max_length=2
            ),
            preserve_default=False,
        ),
    ]
