# Generated by Django 5.0.1 on 2024-05-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0016_patientstate_code_patientstate_unique_code_stateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientstate',
            name='data',
        ),
        migrations.AddField(
            model_name='patientstate',
            name='examination_codes',
            field=models.JSONField(default={}, help_text='List of pairs of examination types and examination codes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientstate',
            name='special_events',
            field=models.CharField(blank=True, help_text='Perceivable events of high priority, e.g. "Patient schreit vor Schmerzen"', null=True),
        ),
        migrations.AddField(
            model_name='patientstate',
            name='vital_signs',
            field=models.JSONField(default={}, help_text='data for patient in current phase'),
            preserve_default=False,
        ),
    ]
