# Generated by Django 5.0.1 on 2024-05-23 18:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0017_alter_patientinformation_triage"),
        ("template", "0017_remove_patientstate_data_and_more"),
    ]

    operations = []
