# Generated by Django 5.0.1 on 2024-05-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("template", "0014_merge_0013_action_results_0013_patientinformation"),
        ("template", "0017_resource_category"),
    ]

    operations = []
