# Generated by Django 5.0.1 on 2024-05-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0017_alter_patientinformation_triage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='blood_type',
            field=models.CharField(default='-', max_length=1),
        ),
    ]
