# Generated by Django 5.0.1 on 2024-05-27 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0016_patientstate_code_patientstate_unique_code_stateid"),
        ("template", "0018_rename_data_patientstate_vital_signs_and_more"),
    ]

    operations = []
