# Generated by Django 5.0.1 on 2024-05-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0018_patientinformation_blood_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientstate',
            old_name='data',
            new_name='vital_signs',
        ),
        migrations.AddField(
            model_name='patientstate',
            name='examination_codes',
            field=models.JSONField(default={}, help_text='List of pairs of examination types and examination codes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientstate',
            name='special_events',
            field=models.CharField(default='', help_text='Perceivable events of high priority, e.g. "Patient schreit vor Schmerzen"'),
            preserve_default=False,
        ),
    ]
