# Generated by Django 5.0.1 on 2024-05-27 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("template", "0019_merge_20240527_1023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientstate",
            name="transition",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="template.statetransition",
            ),
            preserve_default=False,
        ),
    ]
