version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dps_training_k:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://youruser:yourpassword@db:5432/yourdbname

volumes:
  postgres_data: