version: '3.8'

services:
  # Database service
  kdps-postgres:
    build:
      context: .
      dockerfile: ./deployment/postgres/Dockerfile
    image: dps_training_k-postgres
    container_name: kdps-postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - .env.${RUN_CONFIG}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Caching service
  kdps-redis:
    image: redis:latest
    container_name: kdps-redis

  # Backend service
  kdps-django:
    build:
      context: .
      dockerfile: ./deployment/django/Dockerfile
    image: dps_training_k-django
    container_name: kdps-django
    restart: unless-stopped
    depends_on:
      - kdps-postgres
      - kdps-redis
    env_file:
      - .env.${RUN_CONFIG}
    environment:
      - RUN_MIGRATIONS=1 # only django should run migrations
    volumes:
      - static_volume:/app/staticfiles
      - .:/app:z
    ports:
      - 8000:8000
    command: uvicorn configuration.asgi:application --host 0.0.0.0 --reload
    stdin_open: true
    tty: true

  # Celery worker service (e.g. scheduled tasks)
  kdps-celeryworker:
    build:
      context: .
      dockerfile: ./deployment/django/Dockerfile
    image: dps_training_k-celeryworker
    container_name: kdps-celeryworker
    env_file:
      - .env.${RUN_CONFIG}
    command: /start-celeryworker
    depends_on:
      - kdps-django

  # Celery beat service (e.g. scheduled tasks)
  kdps-celerybeat:
    build:
      context: .
      dockerfile: ./deployment/django/Dockerfile
    image: dps_training_k-celerybeat
    container_name: kdps-celerybeat
    env_file:
      - .env.${RUN_CONFIG}
    command: /start-celerybeat
    depends_on:
      - kdps-django

  # Nginx service (reverse proxy for Backend)
  kdps-nginx:
    build:
      context: deployment/nginx
    image: dps_training_k-nginx
    container_name: kdps-nginx
    volumes:
      - static_volume:/app/staticfiles
      - ./deployment/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - kdps-django

volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  static_volume: { }
